# Generated by Django 5.1.4 on 2025-02-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('market_cap_rank', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('exchange', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HighLowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('daily_low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_low_data', to='scanner.coin')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=20)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='scanner.coin')),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('daily_relative_volume', models.FloatField(blank=True, null=True)),
                ('rolling_relative_volume', models.FloatField(blank=True, null=True)),
                ('five_min_relative_volume', models.FloatField(blank=True, null=True)),
                ('twenty_min_relative_volume', models.FloatField(blank=True, null=True)),
                ('price_change_5min', models.FloatField(blank=True, null=True)),
                ('price_change_10min', models.FloatField(blank=True, null=True)),
                ('price_change_1hr', models.FloatField(blank=True, null=True)),
                ('price_change_24hr', models.FloatField(blank=True, null=True)),
                ('price_change_7d', models.FloatField(blank=True, null=True)),
                ('circulating_supply', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='scanner.coin')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('patterntype', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(max_length=200)),
                ('entry', models.DecimalField(decimal_places=8, max_digits=20)),
                ('takeprofit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stoploss', models.DecimalField(decimal_places=8, max_digits=20)),
                ('five_min_signal', models.CharField(blank=True, max_length=200, null=True)),
                ('fifteen_min_signal', models.CharField(blank=True, max_length=200, null=True)),
                ('one_hour_signal', models.CharField(blank=True, max_length=200, null=True)),
                ('five_min_adx', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('fifteen_min_adx', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('one_hour_adx', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern', to='scanner.coin')),
            ],
        ),
        migrations.CreateModel(
            name='ShortIntervalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume_5min', models.DecimalField(decimal_places=2, max_digits=20)),
                ('circulating_supply', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_interval_data', to='scanner.coin')),
            ],
        ),
        migrations.CreateModel(
            name='SupportResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_one', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('level_two', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('level_three', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('level_four', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('level_five', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('level_six', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_resistance', to='scanner.coin')),
            ],
        ),
    ]
