# Generated by Django 4.2.8 on 2024-12-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrics",
            name="price_change_1hr",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metrics",
            name="price_change_7d",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
