# Generated by Django 5.1.4 on 2025-02-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggercombination',
            name='success_rate',
        ),
    ]
