# Generated by Django 5.1.4 on 2025-02-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_remove_triggercombination_success_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TriggerCombination',
        ),
    ]
