# Generated by Django 5.1.4 on 2025-03-25 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_firedsignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('move_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('metrics', models.JSONField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.coin')),
            ],
        ),
    ]
