# Generated by Django 4.2.8 on 2024-12-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0003_metrics_twenty_min_relative_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortintervaldata",
            name="circulating_supply",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
