# Generated by Django 5.1.4 on 2025-03-25 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_successfulmove'),
    ]

    operations = [
        migrations.AddField(
            model_name='successfulmove',
            name='entry_metrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.metrics'),
        ),
    ]
