# Generated by Django 4.2.8 on 2024-12-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0004_shortintervaldata_circulating_supply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="coin",
            name="symbol",
            field=models.CharField(max_length=10),
        ),
    ]
