# Generated by Django 5.1.4 on 2025-03-26 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_successfulmove_entry_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('entry_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('success', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.coin')),
                ('entry_metrics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.metrics')),
            ],
        ),
    ]
