# Generated by Django 4.2.8 on 2024-12-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0005_alter_coin_name_alter_coin_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="cmc_id",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coin",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
