# Generated by Django 5.1.4 on 2025-03-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_backtestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='firedsignal',
            name='signal_type',
            field=models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=10),
        ),
    ]
