# Generated by Django 5.1.4 on 2025-04-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_firedsignal_signal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='trade_type',
            field=models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=10),
        ),
    ]
