# Generated by Django 4.2.8 on 2024-12-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0006_coin_cmc_id_alter_coin_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="metrics",
            old_name="relative_volume",
            new_name="rolling_relative_volume",
        ),
        migrations.AddField(
            model_name="metrics",
            name="daily_relative_volume",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
