# Generated by Django 4.2.8 on 2024-12-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scanner",
            "0007_rename_relative_volume_metrics_rolling_relative_volume_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="metrics",
            name="five_min_relative_volume",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
