# Generated by Django 5.1.4 on 2025-04-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_backtestresult_trade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='change_since_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='change_since_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='trend_slope_30min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='volatility_5min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='volume_marketcap_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
