# Generated by Django 4.2.8 on 2025-01-07 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0008_metrics_five_min_relative_volume"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemeCoin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cmc_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("market_cap_rank", models.IntegerField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MemeMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("five_min_relative_volume", models.FloatField(blank=True, null=True)),
                ("price_change_5min", models.FloatField(blank=True, null=True)),
                ("price_change_10min", models.FloatField(blank=True, null=True)),
                ("price_change_1hr", models.FloatField(blank=True, null=True)),
                (
                    "circulating_supply",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "volume_24h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("market_cap", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memeMetrics",
                        to="scanner.memecoin",
                    ),
                ),
            ],
        ),
    ]
