# Generated by Django 5.1.4 on 2025-04-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_metrics_change_since_high_metrics_change_since_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firedsignal',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
