# Generated by Django 5.1.4 on 2025-04-15 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_firedsignal_closed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RickisMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('high_24h', models.DecimalField(decimal_places=10, max_digits=20)),
                ('change_5m', models.FloatField()),
                ('change_1h', models.FloatField()),
                ('change_24h', models.FloatField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=30)),
                ('avg_volume_1h', models.DecimalField(decimal_places=2, max_digits=30)),
                ('rsi', models.FloatField(null=True)),
                ('macd', models.FloatField(null=True)),
                ('macd_signal', models.FloatField(null=True)),
                ('stochastic_k', models.FloatField(null=True)),
                ('stochastic_d', models.FloatField(null=True)),
                ('support_level', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('resistance_level', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.coin')),
            ],
        ),
    ]
