# Generated by Django 5.1.4 on 2025-04-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_rickismetrics'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shortintervaldata',
            index=models.Index(fields=['coin', 'timestamp'], name='coin_timestamp_idx'),
        ),
    ]
