# Generated by Django 5.1.4 on 2025-01-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0010_memeshortintervaldata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memecoin",
            old_name="last_updated",
            new_name="date_added",
        ),
        migrations.AlterField(
            model_name="mememetric",
            name="market_cap",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="metrics",
            name="market_cap",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
