# Generated by Django 5.1.4 on 2025-01-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0011_rename_last_updated_memecoin_date_added_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="exchange",
            field=models.CharField(default="BINANCE:BTCUSDT", max_length=100),
            preserve_default=False,
        ),
    ]
