# Generated by Django 5.1.4 on 2025-04-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0011_shortintervaldata_coin_timestamp_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='rickismetrics',
            name='atr_1h',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='ema_12',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='ema_26',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='price_slope_1h',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='relative_volume',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='sma_20',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='sma_5',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='stddev_1h',
            field=models.FloatField(null=True),
        ),
    ]
