# Generated by Django 5.1.4 on 2025-01-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0012_coin_exchange"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trigger_name", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
