# Generated by Django 5.1.4 on 2025-01-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0013_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaldata",
            name="daily_high",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaldata",
            name="daily_low",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
