# Generated by Django 5.1.4 on 2025-04-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_rickismetrics_long_result_rickismetrics_short_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rickismetrics',
            name='low_24h',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
