# Generated by Django 5.1.4 on 2025-04-27 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_rickismetrics_low_24h_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rickismetrics',
            name='unique_coin_timestamp_rickis',
        ),
    ]
