# Generated by Django 5.1.4 on 2025-05-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_rickismetrics_low_24h'),
    ]

    operations = [
        migrations.AddField(
            model_name='rickismetrics',
            name='market_sentiment_label',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='market_sentiment_score',
            field=models.IntegerField(null=True),
        ),
    ]
