# Generated by Django 5.1.4 on 2025-02-01 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_historicaldata_daily_high_historicaldata_daily_low'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldata',
            name='daily_high',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='daily_low',
        ),
        migrations.CreateModel(
            name='HighLowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('daily_low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_low_data', to='scanner.coin')),
            ],
        ),
    ]
