# Generated by Django 5.1.4 on 2025-02-03 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0015_remove_historicaldata_daily_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlowdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('patterntype', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('entry', models.DecimalField(decimal_places=8, max_digits=20)),
                ('takeprofit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stoploss', models.DecimalField(decimal_places=8, max_digits=20)),
                ('support', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('resistance', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('five_min_signal', models.CharField(max_length=200, null=True)),
                ('fifteen_min_signal', models.CharField(max_length=200, null=True)),
                ('one_hour_signal', models.CharField(max_length=200, null=True)),
                ('five_min_adx', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('fifteen_min_adx', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('one_hour_adx', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern', to='scanner.coin')),
            ],
        ),
    ]
