# Generated by Django 5.1.4 on 2025-05-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0016_rickismetrics_change_since_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rickismetrics',
            name='adx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='bollinger_lower',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='bollinger_middle',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='bollinger_upper',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='fib_distance_0_236',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='fib_distance_0_382',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='fib_distance_0_5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='fib_distance_0_618',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='fib_distance_0_786',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='obv',
            field=models.FloatField(null=True),
        ),
    ]
