# Generated by Django 5.1.4 on 2025-02-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0016_alter_highlowdata_timestamp_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='fifteen_min_adx',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='fifteen_min_signal',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='five_min_adx',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='five_min_signal',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='one_hour_adx',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='one_hour_signal',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='patterntype',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='resistance',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='stoploss',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='support',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='takeprofit',
        ),
    ]
