# Generated by Django 5.1.4 on 2025-05-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0017_rickismetrics_adx_rickismetrics_bollinger_lower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rickismetrics',
            name='close',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='open',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
