# Generated by Django 5.1.4 on 2025-02-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0017_remove_pattern_entry_remove_pattern_fifteen_min_adx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='entry',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='fifteen_min_adx',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='fifteen_min_signal',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='five_min_adx',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='five_min_signal',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='one_hour_adx',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='one_hour_signal',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='patterntype',
            field=models.CharField(default='pattern', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='resistance',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='status',
            field=models.CharField(default='status', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='stoploss',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='support',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='takeprofit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
