# Generated by Django 5.1.4 on 2025-05-05 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0018_rickismetrics_close_rickismetrics_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=5)),
                ('entry_timestamp', models.DateTimeField()),
                ('exit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('entry_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('model_confidence', models.FloatField()),
                ('take_profit_percent', models.FloatField()),
                ('stop_loss_percent', models.FloatField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('result', models.BooleanField(blank=True, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.coin')),
            ],
        ),
    ]
