# Generated by Django 5.1.4 on 2025-06-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0020_realtrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrade',
            name='confidence_trade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
