# Generated by Django 5.1.4 on 2025-06-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0021_modeltrade_confidence_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='rickismetrics',
            name='chart_pattern_15m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='chart_pattern_5m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rickismetrics',
            name='chart_pattern_60m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
