# Generated by Django 5.1.4 on 2025-06-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0022_rickismetrics_chart_pattern_15m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rickismetrics',
            name='fear_greed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
