# Generated by Django 5.1.4 on 2025-06-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0025_binanceprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BinancePrice',
            new_name='CoinAPIPrice',
        ),
        migrations.RenameIndex(
            model_name='coinapiprice',
            new_name='scanner_coi_coin_ff749f_idx',
            old_name='scanner_bin_coin_89a0b7_idx',
        ),
    ]
