# Generated by Django 5.2.3 on 2025-06-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0026_rename_binanceprice_coinapiprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinapiprice',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
