# Generated by Django 5.2.3 on 2025-06-12 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0027_alter_coinapiprice_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=10, max_digits=20)),
                ('high', models.DecimalField(decimal_places=10, max_digits=20)),
                ('low', models.DecimalField(decimal_places=10, max_digits=20)),
                ('close', models.DecimalField(decimal_places=10, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=30)),
                ('sma_5', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('sma_20', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('ema_12', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('ema_26', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('ema_crossover_flag', models.BooleanField(null=True)),
                ('rsi', models.FloatField(null=True)),
                ('macd', models.FloatField(null=True)),
                ('macd_signal', models.FloatField(null=True)),
                ('stochastic_k', models.FloatField(null=True)),
                ('stochastic_d', models.FloatField(null=True)),
                ('bollinger_upper', models.FloatField(null=True)),
                ('bollinger_middle', models.FloatField(null=True)),
                ('bollinger_lower', models.FloatField(null=True)),
                ('adx', models.FloatField(null=True)),
                ('atr_1h', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('stddev_1h', models.FloatField(null=True)),
                ('momentum_10', models.FloatField(null=True)),
                ('momentum_50', models.FloatField(null=True)),
                ('roc', models.FloatField(null=True)),
                ('rolling_volatility_5h', models.FloatField(null=True)),
                ('rolling_volatility_24h', models.FloatField(null=True)),
                ('high_low_ratio', models.FloatField(null=True)),
                ('price_position', models.FloatField(null=True)),
                ('candle_body_size', models.FloatField(null=True)),
                ('candle_body_pct', models.FloatField(null=True)),
                ('wick_upper', models.FloatField(null=True)),
                ('wick_lower', models.FloatField(null=True)),
                ('slope_5h', models.FloatField(null=True)),
                ('slope_24h', models.FloatField(null=True)),
                ('trend_acceleration', models.FloatField(null=True)),
                ('fib_distance_0_236', models.FloatField(null=True)),
                ('fib_distance_0_382', models.FloatField(null=True)),
                ('fib_distance_0_618', models.FloatField(null=True)),
                ('vwap', models.FloatField(null=True)),
                ('volume_price_ratio', models.FloatField(null=True)),
                ('volume_change_5m', models.FloatField(null=True)),
                ('volume_surge', models.FloatField(null=True)),
                ('overbought_rsi', models.BooleanField(null=True)),
                ('oversold_rsi', models.BooleanField(null=True)),
                ('upper_bollinger_break', models.BooleanField(null=True)),
                ('lower_bollinger_break', models.BooleanField(null=True)),
                ('atr_normalized', models.FloatField(null=True)),
                ('short_vs_long_strength', models.FloatField(null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.coin')),
            ],
            options={
                'unique_together': {('coin', 'timestamp')},
            },
        ),
    ]
