# Generated by Django 5.2.3 on 2025-06-12 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0028_livemodelmetrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern',
            old_name='name',
            new_name='patternname',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='fifteen_min_adx',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='fifteen_min_signal',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='five_min_adx',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='five_min_signal',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='one_hour_adx',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='one_hour_signal',
        ),
        migrations.AddField(
            model_name='pattern',
            name='adx',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='resolution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='scanner.coin'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='entry',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='stoploss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='takeprofit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
