# Generated by Django 5.2.3 on 2025-06-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0029_rename_name_pattern_patternname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtrade',
            old_name='account_balance',
            new_name='account_balance_before',
        ),
        migrations.AddField(
            model_name='realtrade',
            name='account_balance_after',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
