# Generated by Django 5.2.3 on 2025-06-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0030_rename_account_balance_realtrade_account_balance_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtrade',
            name='exit_usd_amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
