# Generated by Django 5.2.3 on 2025-07-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0032_modeltrade_model_name_confidencehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrade',
            name='recent_confidences',
            field=models.JSONField(blank=True, help_text='Last 6 confidence scores', null=True),
        ),
    ]
