# Generated by Django 5.2.3 on 2025-07-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0033_modeltrade_recent_confidences'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('open', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('high', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('low', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('close', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('volume', models.DecimalField(decimal_places=10, max_digits=30, null=True)),
            ],
            options={
                'unique_together': {('coin',)},
            },
        ),
    ]
