# Generated by Django 5.2.3 on 2025-07-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0035_livechart'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('trade_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('features', models.JSONField()),
                ('ml_confidence', models.FloatField()),
                ('gpt_confidence', models.FloatField(blank=True, null=True)),
                ('leverage', models.FloatField(default=15.0)),
                ('tp_percent', models.FloatField(default=0.02)),
                ('sl_percent', models.FloatField(default=-0.01)),
                ('chart_image', models.ImageField(blank=True, null=True, upload_to='memory_charts/')),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('exit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('open', 'Open')], default='open', max_length=10)),
            ],
        ),
    ]
